### ISSUE TITLE
Plan to Pull Kraken Support

### ISSUE THREAD

**Issue by Brandin** [nicklaw5/twitch-api-php#110]
Kraken is considered legacy and no longer supported, and migrations are available for all endpoints.

**Comment by brandinarsenault** [comment]
After a few smart remarks from others, finally got some thoughts from an admin in the TwitchDev Discord, they recommend keeping it until Twitch actually removes it. Will follow through with info removal in #82 but not remove it from the code for the near future. Will keep ticket open.

**Comment by ThibaultVlacich** [comment]
> Today we are announcing the timeline to decommission the Legacy Twitch API v5 with the shutdown to be completed on February 28, 2022. Twitch application client IDs must migrate to the Twitch API by February 28, 2022, and those that have not made requests to the v5 API before July 15, 2021 will no longer be able to access v5.

https://discuss.dev.twitch.tv/t/legacy-twitch-api-v5-shutdown-details-and-timeline/32649
