### ISSUE TITLE
Hype train events

### ISSUE THREAD

**Issue by alitnk** [nicklaw5/twitch-api-php#113]
Hey, thanks for the package.

Just wanted to know when will this endpoint be covered in webhooks?
https://dev.twitch.tv/docs/api/webhooks-reference#topic-hype-train-event

**Comment by brandinarsenault** [comment]
Further webhooks are unlikely to be implemented as EventSub is considered a superior method. There is a WIP PR for this.
Per Twitch:
> Just getting started with Twitch webhooks? Try using [EventSub](https://dev.twitch.tv/docs/eventsub), Twitch’s transport-neutral events solution that makes subscribing to events easier than ever.

**Comment by alitnk** [comment]
Thanks for the response.

Will the PR be added anytime soon?

**Comment by brandinarsenault** [comment]
Whenever the user finishes the PR.
