### ISSUE TITLE
Client Errors for 5.0

### ISSUE THREAD

**Issue by brandinarsenault** [nicklaw5/twitch-api-php#126]
#121 introduced more errors than expected. Although I tested it, it seems I may have been using the wrong version in my testing and I did not notice the errors. Fortunately, it seems nobody has tested the new version yet...or we probably would've gotten a notice!

`Argument 1 passed to NewTwitchApi\NewTwitchApi::__construct() must be an instance of GuzzleHttp\Client`

Naturally, I would think "well I just need to change the Class in the `NewTwitchApi`...worked...then I needed to do `AbstractResource` and `WebhooksSubscriptionApi`...but then other API errors are introduced that were unexpected since we are no longer extending the `Guzzle\Client`, for example, our class does not have the `send` method (or any method, for that matter other than `getClient`...

The easiest solution seems to be to rollback #121 for the time being to get the library working again, and we'll try doing the change in a future release.

Thoughts @echosa and @ThibaultVlacich?

**Comment by echosa** [comment]
I'd rather not rollback. I don't think we need to. Since 5.0 was a major version change and seems "broken", any clients using this library can just go back to/continue using pre-5.0 versions. If they're using 5.0, they're already experiencing this breakage anyway. 

I'd say just fix the issues in 5.0 and push it.

**Comment by ThibaultVlacich** [comment]
I am using the changes I made in #121, and as stated in the PR it requires some changes to the code, as documented in the Readme.

```php
$helixGuzzleClient = \NewTwitchApi\HelixGuzzleClient::getClient($twitch_client_id);
$newTwitchApi = new \NewTwitchApi\NewTwitchApi($helixGuzzleClient, $twitch_client_id, $twitch_client_secret);
```

Instead of:
```php
$newTwitchApi = new \NewTwitchApi\NewTwitchApi($helixGuzzleClient, $twitch_client_id, $twitch_client_secret);
$newTwitchApi = new \NewTwitchApi\NewTwitchApi($helixGuzzleClient, $twitch_client_id, $twitch_client_secret);
```

(Make sure to remove the `new` keyword!)

**Comment by brandinarsenault** [comment]
Interesting...okay...that does work for me...

Now, do we want to recommend this new method of code for v5 or do we want to rework the HelixGuzzleClient class to be a working middleware? (similar to how they've done it in CloudFlare's library - https://github.com/cloudflare/cloudflare-php/blob/master/src/Adapter/Guzzle.php)

I'm working on the second, and its working for everything except the WebhooksSubscriptionsApi (WHY DID THIS EVER EXIST TWITCH!!!) because its not using our Request Generator and needs a refactor. After that, I see no reason it won't work, and then developers wouldn't need to make any changes at all.

**Comment by ThibaultVlacich** [comment]
I think the way Cloudflare is doing it is better / cleaner, I wish I would have thought of doing it that way initially :D

**Comment by brandinarsenault** [comment]
This refactor of the Webhooks API is going to be very painful...and with EventSub now in, and Twitch actually recommending it over Webhooks, it would be nice to pull it over refactoring this whole API and Spec. Thoughts @echosa?

**Comment by echosa** [comment]
At this point, I touch this code much less than you and don't really use any of the features added since I stopped mainline working on it. I trust the future to you. However you see fit to get this library back up to code (pun intended) is good with me. I'm happy to review changes and add specific code-related input then.

**Comment by brandinarsenault** [comment]
Seems like the best method is adding our own middleware which I'm continuing in #127. As for the Webhooks, I'll definitely remove them in favor for EventSub due to Twitch's recommendation.
