### ISSUE TITLE
Webhooks support

### ISSUE THREAD

**Issue by echosa** [nicklaw5/twitch-api-php#13]
Are there any plans to add calling into webhooks from this API? 

https://dev.twitch.tv/docs/api/webhooks-guide

**Comment by nicklaw5** [comment]
The library's current state only caters to Twitch's v3 & v5 APIs. Twitch's webhook implementation has only been introduced by their newest API, Helix. I am hoping to  make a start on the Helix integration in the near future (see #11). That will likely happen once I'm finished on [my Go implementation of the Helix API](https://github.com/nicklaw5/helix).

**Comment by echosa** [comment]
Awesome, thanks! I'll keep an eye out. 👍 Free free to close this if it duplicates #11, or keep it open if it acts as a separate effort.
