### ISSUE TITLE
Refresh Token & createChannelStreamScheduleSegment

### ISSUE THREAD

**Issue by sbc-mining** [nicklaw5/twitch-api-php#141]
Hello,

I'm currently trying to edit the schedule on Twitch with the API.

Currently I always get the error that the OAUTH token is missing. But I enter it as follows:
""error":"Unauthorized","status":401,"message":"Missing User OAUTH Token""

`$response = $twitchApi->getScheduleApi()->createChannelStreamScheduleSegment($twitch_access_token,$twitchid,$schedulestarttime,$scheduletimezone, false, $additionalBodyParams);`

I also have the variable $twitch_access_token output beforehand and it is definitely not empty.

I believe the problem arises before that as I have the token updated and I have the code here from the examples. There you can find an example to renew the access token.
However, the example says `"$token = $oauth->getAppAccessToken($twitch_scopes ?? '');"`
which then looks to me that the example is not for the client user token at all, but for the AppToken. Because normally you would have to use the refresh token to get a new token, which I can't find in the example.
According to Twitch Api I would also get a new Refresh_Token which I should save for the next time, but the output is also missing in the example. So I suspect that this is really only for an app token.

For this purpose, the `"createChannelStreamScheduleSegment"` always expects a duration. According to Twitch, this is actually optional.

So can someone help me on how to renew my User Access Token?

**Comment by Brandin** [comment]
In the future, I would encourage you to look through the class files before posting to see if you can locate the function. Doing a project search for the function you're already able to find `getAppAcessToken` or how to get the user token described in README (`getUserAccessToken`) would lead you to `src/OauthApi.php`. In this file, which is the OAuth API you've initialized in the example in the README, you'll see a function `refreshToken` described here:
https://github.com/nicklaw5/twitch-api-php/blob/master/src/Auth/OauthApi.php#L61

I'm also not seeing where `duration` is required in our function `createChannelStreamScheduleSegment`:
https://github.com/nicklaw5/twitch-api-php/blob/master/src/Resources/ScheduleApi.php#L95
