### ISSUE TITLE
Update Travis CI to run new processes

### ISSUE THREAD

**Issue by echosa** [nicklaw5/twitch-api-php#23]
https://github.com/nicklaw5/twitch-api-php/pull/22 introduces a couple of new dev tools, namely `phpspec` and `php-cs-fixer`. We should get CI to run at least `phpspec`, if not also `php-cs-fixer`, once that PR is merged.

**Comment by nicklaw5** [comment]
#27 adds `phpspec` to CI. Leaving this open until we get around to adding `php-cs-fixer`.
