### ISSUE TITLE
Add missing New Twitch API endpoints

### ISSUE THREAD

**Issue by echosa** [nicklaw5/twitch-api-php#24]
Continuing from https://github.com/nicklaw5/twitch-api-php/issues/11 the rest of the New Twitch API endpoints should be added.

*Channel Points*
- [x] https://dev.twitch.tv/docs/api/reference#create-custom-rewards
- [x] https://dev.twitch.tv/docs/api/reference#delete-custom-reward
- [x] https://dev.twitch.tv/docs/api/reference#update-custom-reward
- [x] https://dev.twitch.tv/docs/api/reference#update-redemption-status

*Entitlements*
- [x] https://dev.twitch.tv/docs/api/reference#create-entitlement-grants-upload-url
- [x] https://dev.twitch.tv/docs/api/reference#get-drops-entitlements

*Moderation*
- [x] https://dev.twitch.tv/docs/api/reference#check-automod-status

*Streams*
- [x] https://dev.twitch.tv/docs/api/reference#create-stream-marker
- [x] https://dev.twitch.tv/docs/api/reference#modify-channel-information

*Tags*
- [ ] https://dev.twitch.tv/docs/api/reference#replace-stream-tags

*Users* 
- [x] https://dev.twitch.tv/docs/api/reference#update-user
- [x] https://dev.twitch.tv/docs/api/reference#delete-user-follows
- [ ] https://dev.twitch.tv/docs/api/reference#update-user-extensions

*Webhooks*
- [ ] https://dev.twitch.tv/docs/api/webhooks-reference#topic-hype-train-event

*EventSub*
- [ ] https://dev.twitch.tv/docs/eventsub

**Comment by brandinarsenault** [comment]
Here is a list of missing endpoints:

*Analytics*
https://dev.twitch.tv/docs/api/reference#get-extension-analytics**
https://dev.twitch.tv/docs/api/reference#get-game-analytics

*Bits*
https://dev.twitch.tv/docs/api/reference#get-bits-leaderboard
https://dev.twitch.tv/docs/api/reference#get-extension-transactions

*Clips*
https://dev.twitch.tv/docs/api/reference#create-clip

*Entitlements* 
https://dev.twitch.tv/docs/api/reference#create-entitlement-grants-upload-url
https://dev.twitch.tv/docs/api/reference#get-code-status
https://dev.twitch.tv/docs/api/reference#redeem-code

*Moderation*
https://dev.twitch.tv/docs/api/reference#check-automod-status

*Streams*
https://dev.twitch.tv/docs/api/reference#create-stream-marker

*Tags*
https://dev.twitch.tv/docs/api/reference#get-all-stream-tags
https://dev.twitch.tv/docs/api/reference#get-stream-tags
https://dev.twitch.tv/docs/api/reference#replace-stream-tags

*Users* 
https://dev.twitch.tv/docs/api/reference#update-user

**Comment by brandinarsenault** [comment]
I've updated https://github.com/nicklaw5/twitch-api-php/issues/24#issuecomment-641606606 with new endpoints released but not yet added.

**Comment by echosa** [comment]
Thank you for being so vigilant!

**Comment by brandinarsenault** [comment]
Resolved the following two in PR #66: 
https://dev.twitch.tv/docs/api/reference#start-commercial
https://dev.twitch.tv/docs/api/reference#create-clip

**Comment by echosa** [comment]
New version released with those two endpoints: https://github.com/nicklaw5/twitch-api-php/releases/tag/v3.0.1

**Comment by MaxHayman** [comment]
added https://dev.twitch.tv/docs/api/reference/#create-entitlement-grants-upload-url

https://github.com/nicklaw5/twitch-api-php/pull/70

**Comment by brandinarsenault** [comment]
Code for `modifyChannelInfo` - need `PatchApi` call
`    /**
     * @throws GuzzleException
     * @link https://dev.twitch.tv/docs/api/reference#modify-channel-information
     */
    public function modifyChannelInfo(string $bearer, string $broadcasterId, string $status = null, string $gameId = null, string $broadcasterLanguage = null, string $title = null, string $description = null): ResponseInterface
    {
        $queryParamsMap = [];

        $queryParamsMap[] = ['key' => 'broadcaster_id', 'value' => $broadcasterId];

        if ($status) {
            $queryParamsMap[] = ['key' => 'status', 'value' => $status];
        }

        if ($gameId) {
            $queryParamsMap[] = ['key' => 'game_id', 'value' => $gameId];
        }

        if ($broadcasterLanguage) {
            $queryParamsMap[] = ['key' => 'broadcaster_language', 'value' => $broadcasterLanguage];
        }

        if ($title) {
            $queryParamsMap[] = ['key' => 'title', 'value' => $title];
        }

        if ($description) {
            $queryParamsMap[] = ['key' => 'description', 'value' => $description];
        }

        return $this->postApi('channels', $bearer, $queryParamsMap);
    }`

**Comment by brandinarsenault** [comment]
Need `PutApi` and `DeleteApi` call for further endpoints

**Comment by brandinarsenault** [comment]
Resolved in #74 
- BitsApi->getExtensionTransactions
- AnalyticsApi->getExtensionAnalytics
- AnalyticsApi->getGameAnalytics
- EntitlementsApi->getStatusCode
- EntitlementsApi->redeemCode
- TagsApi->getAllStreamTags
- TagsApi->getStreamTags
- UsersApi->createUserFollow

**Comment by brandinarsenault** [comment]
Updated list of missing endpoints:

*Moderation*
- [ ] https://dev.twitch.tv/docs/api/reference#check-automod-status

*Streams*
- [ ] https://dev.twitch.tv/docs/api/reference#create-stream-marker
- [ ] https://dev.twitch.tv/docs/api/reference#modify-channel-information

*Tags*
- [ ] https://dev.twitch.tv/docs/api/reference#replace-stream-tags

*Users* 
- [ ] https://dev.twitch.tv/docs/api/reference#update-user
- [ ] https://dev.twitch.tv/docs/api/reference#delete-user-follows

*Webhooks*
- [ ] https://dev.twitch.tv/docs/api/webhooks-reference#topic-hype-train-event

**Comment by echosa** [comment]
@brandinarsenault I have copied your latest updated list into the issue description. It'll be easier to find and reference there, rather than having to dig through the comments.

**Comment by brandinarsenault** [comment]
Updated list of missing endpoints:


*Channel Points*
- [ ] https://dev.twitch.tv/docs/api/reference#create-custom-rewards
- [ ] https://dev.twitch.tv/docs/api/reference#delete-custom-reward
- [ ] https://dev.twitch.tv/docs/api/reference#update-custom-reward
- [ ] https://dev.twitch.tv/docs/api/reference#update-redemption-status

*Entitlements*
- [ ] https://dev.twitch.tv/docs/api/reference#create-entitlement-grants-upload-url
- [ ] https://dev.twitch.tv/docs/api/reference#get-drops-entitlements

*Moderation*
- [ ] https://dev.twitch.tv/docs/api/reference#check-automod-status

*Streams*
- [ ] https://dev.twitch.tv/docs/api/reference#create-stream-marker
- [ ] https://dev.twitch.tv/docs/api/reference#modify-channel-information

*Tags*
- [ ] https://dev.twitch.tv/docs/api/reference#replace-stream-tags

*Users* 
- [ ] https://dev.twitch.tv/docs/api/reference#update-user
- [x] https://dev.twitch.tv/docs/api/reference#delete-user-follows
- [ ] https://dev.twitch.tv/docs/api/reference#update-user-extensions

*Webhooks*
- [ ] https://dev.twitch.tv/docs/api/webhooks-reference#topic-hype-train-event

*EventSub*
- [ ] https://dev.twitch.tv/docs/eventsub

**Comment by brandinarsenault** [comment]
Moved to #108
