### ISSUE TITLE
PHPDocs

### ISSUE THREAD

**Issue by zanderwar** [nicklaw5/twitch-api-php#33]
Love how detailed the PHPDocs are, thank you - one minor issue is that `json` is not a valid `@return` type. Instead, it's many instances should be `string`

PHPStorm, in particular, will cry about this when inheriting PHPDocs (making a wrapper using this library)

If you agree I'm happy to PR in the changes, thanks

**Comment by nicklaw5** [comment]
Hi @zanderwar. Thanks for letting us know. I doubt we'll get to this ourselves. Happy to accept a PR if you want to look into this yourself.
