### ISSUE TITLE
The "testApiVersionDefaultsTo5IfNotSpecificallySet" is specifying the api version

### ISSUE THREAD

**Issue by RickyNotaro** [nicklaw5/twitch-api-php#4]
Hello, as seen [there](https://github.com/nicklaw5/twitch-api-php/blob/54eb9a9c7bd33eb3c7403038894cf788a3447088/test/TwitchApiTest.php#L53), the "testApiVersionDefaultsTo5IfNotSpecificallySet" test case introduced in [this commit](https://github.com/nicklaw5/twitch-api-php/commit/d8d8d589ac71097d05039900e302d8629e2d7040) is wrongfully specifying the api version 5 when initializing the TwichApi object.

**Comment by nicklaw5** [comment]
Closed via #5
