### ISSUE TITLE
Use >= PHP 7.1 syntax

### ISSUE THREAD

**Issue by b3none** [nicklaw5/twitch-api-php#41]
I believe that this is for the best since PHP 5 was deprecated.

**Comment by b3none** [comment]
Fixed by #43

**Comment by echosa** [comment]
I agree! Thanks for the PRs updating the README. I've merged them in. I think the code is already mostly 7.1, even though the README had still said otherwise. Do you see any code changes that are necessary to be 7.1-compatible? Happy to accept another PR.

**Comment by b3none** [comment]
Firstly, thanks for merging my PRs.

Figure I'd be better adding some clarification:
```php
/**
 * Get defaultApiVersion
 *
 * @return int
 */
public function getDefaultApiVersion()
{
    return $this->defaultApiVersion;
}
```

What I am getting at is that this could perhaps be updated with return types etc.

i.e.
```php
/**
 * Get defaultApiVersion
 *
 * @return int
 */
public function getDefaultApiVersion(): int
{
    return $this->defaultApiVersion;
}
```

If I get the time I'll submit a PR with the updates but no promises! :)

**Comment by echosa** [comment]
I'll say this: keep in mind that half this codebase is the "old" API, and that code is still old PHP and will possibly/likely go away at some point. If that's what you're looking at updating, I'm not sure it's worth it. All the code in the `NewTwitchApi` namespaces is new and should already be PHP 7.1 compatible.

**Comment by b3none** [comment]
Personally I'd say make a final release of the old one and bump the version then make another release with the new one in its place.

**Comment by echosa** [comment]
The issue with that is not all APIs are available in the New Twitch API yet (as in Twitch hasn't developed/released them). So in order to get the functionality missing in the New Twitch API, you still need to use the old API. For that reason, I've kept them side-by-side so that users (myself included) of this library can download the library and have access to the new API and the old API for calls Twitch has not yet migrated or released in the new API.

**Comment by b3none** [comment]
When you put it that way you're probably right. I'm going to submit a PR to the new stuff in the next minute or so containing doc blocks as well as switching out private where not necessary imho

**Comment by echosa** [comment]
This should have been handled in #61. Closing. Please reopen with explanation if something else still needs to be done.
