### ISSUE TITLE
Videos and Clips

### ISSUE THREAD

**Issue by boredom2** [nicklaw5/twitch-api-php#47]
Hi there,

I know, there is another Ticket with "missing Endpoints in NewAPI".
Nevertheless, is it likely, that you will add the Endpoints /videos and /clips for NewAPI anytime soon? Those are basically the most important Endpoints for us.

Thanks a lot!
Christoph

**Comment by echosa** [comment]
@boredom2 I can try to get it in, but I'm currently in the middle of moving between homes so life's a bit busy. Is it something you could add and test, then PR to us to review?

**Comment by boredom2** [comment]
@echosa Thanks, I understand. I can ask someone from our Team, if he can give it a shot. 
Happy moving :)

**Comment by brandinarsenault** [comment]
@boredom2 has your team made progress on this? I don't want to begin a PR if you are already working on it.

**Comment by boredom2** [comment]
Hi there. Coming back to this Issue :)
I saw, that someone made some Progress at least for the /videos APIs - but I think, its not yet merged/released?
I saw it hapopening here: https://github.com/nicklaw5/twitch-api-php/pull/50.

What is the Status of this?

Thanks!
Christoph

**Comment by brandinarsenault** [comment]
As far as I'm aware, this was merged but the composer package was never updated.

**Comment by brandinarsenault** [comment]
The progress in #50 was merged but never updated in the composer repo. Nothing new has been done since then as far as I'm aware.

**Comment by boredom2** [comment]
Do you plan to "officially" merge and update the Composer Repo accordingly?

**Comment by echosa** [comment]
Ah, I need to create a new release of the project here on GitHub. I'll do that today. Sorry for the delay! 

FTR, you can always use the latest code by telling your composer to pull `dev-master`.

**Comment by echosa** [comment]
Version 2.1.2 has just been created. I'm not sure how/when packagist will get the updated, but I assume it should be soon.

**Comment by boredom2** [comment]
Wow, thanks for that fast Processing :)

**Comment by echosa** [comment]
You're welcome! Sorry again for the delay! This is a side project for me, and often gets left on the backburner. Reminders are good! :-)
