### ISSUE TITLE
Copy/Paste error returns wrong API

### ISSUE THREAD

**Issue by AlmostInteractive** [nicklaw5/twitch-api-php#52]
https://github.com/nicklaw5/twitch-api-php/blob/e9bc5980cb243c539391b07585aa0cba0543b964/src/NewTwitchApi/NewTwitchApi.php#L68

`getVideosApi` should return an instance of `VideosApi` not `UsersApi`.  See lines 63 and 73 for more errors.

**Comment by AlmostInteractive** [comment]
I just made a PR instead of being lazy. :+1:

**Comment by echosa** [comment]
Thanks!
