### ISSUE TITLE
Ensure Helix API allows authentication for all Endpoints

### ISSUE THREAD

**Issue by brandinarsenault** [nicklaw5/twitch-api-php#55]
I haven't had a chance to check all of the endpoints and I will when I can, but I wanted to open this to keep us all on alert that all Helix endpoints require authentication now, need to ensure this flows through all the endpoints we have in the wrapper

**Comment by echosa** [comment]
> all Helix endpoints require authentication now

I wasn't aware of this! Thanks for the ticket, @brandinarsenault. This library does what I need, so I haven't found much time to work on it lately.

**Comment by brandinarsenault** [comment]
First modification in PR #56 - just happened to come across some failing API calls today so figured I'd push this along. They're returning 401s for everything without a token now, was seemingly a fairly fast transition.

**Comment by brandinarsenault** [comment]
Bearer Token was demanded for the new Clips API in #59

**Comment by brandinarsenault** [comment]
I have my items ready to PR to close this ticket but want to keep it separate from the Clips API, unless you'd rather me push it all together, let me know @echosa or @nicklaw5
