### ISSUE TITLE
Streams::getLiveStreams channel attribute

### ISSUE THREAD

**Issue by romanzipp** [nicklaw5/twitch-api-php#6]
The `channel` variable ist checked for `string` but used in the `foreach` loop afterwards resulting in 

```
PHP Warning:  Invalid argument supplied for foreach() in ...nicklaw5/twitch-api-php/src/Api/Streams.php on line 60
```

**Comment by nicklaw5** [comment]
Thanks for the report @romanzipp. That has been fixed, and I've released v0.1.2 :smiley:
