### ISSUE TITLE
Create Missing Specs for Ads and Clips Api

### ISSUE THREAD

**Issue by Brandin** [nicklaw5/twitch-api-php#67]
As per PR #66 we need Specs for the new Ads and Clips API - low priority but will get this done with time

Specs required:
- [x] Ads->ALL
- [x] Bits->getBitsLeaderboard
- [x] Clips->ALL
- [x] Entitlements->getEntitlementGrantsUploadURL
- [x] HypeTrain->ALL
- [x] Moderation->ALL
- [x] Search->ALL
- [x] Streams->SOME
- [x] Subscriptions->ALL
- [x] Users->SOME
- [x] Videos->ALL
- [x] Webhooks->SOME?

**Comment by echosa** [comment]
Thank you!
