### ISSUE TITLE
Name to ID

### ISSUE THREAD

**Issue by romanzipp** [nicklaw5/twitch-api-php#7]
Could you add the endpoint for name to id translations?

This would be:

```
https://api.twitch.tv/kraken/users?login={name}
```
(v5 API)

**Comment by nicklaw5** [comment]
I sure can, I wasn't actually aware this was a thing. I'll get to it today.

**Comment by nicklaw5** [comment]
@romanzipp the `getUserByUsername` method has been added in 1c17b21.

I will release a new version once I'm finished adding the collection endpoints, but if you need this method now, just have composer pull down `dev-master` instead of a specific version.
