### ISSUE TITLE
Add Root /kraken Enpoint

### ISSUE THREAD

**Issue by romanzipp** [nicklaw5/twitch-api-php#8]
The `/kraken` Endpoint identifies if an OAuth token is still valid.

Documentation: https://dev.twitch.tv/docs/v5/guides/using-the-twitch-api/#requests

### Details:
GET `https://api.twitch.tv/kraken` (with OAuth Authorization)

#### VALID  Response
```json
{
  "token": {
    "valid": true,
    "authorization": {
      "scopes": [
        "user_read"
      ],
      "created_at": "2017-04-24T14:09:17Z",
      "updated_at": "2017-04-24T14:09:17Z"
    },
    "user_name": "...",
    "user_id": "...",
    "client_id": "..."
  },
}
```

#### INVALID  Response
```json
{
  "token": {
    "valid": false,
    "authorization": null
  }
}
```

**Comment by nicklaw5** [comment]
Thanks for pointing that out @romanzipp.

I've added the `validateAccessToken($myAccessToken)` for handling these requests (see 39a461c93cdca4030a0b849a7434342cdf8a3901). I've also published a new release.
