### ISSUE TITLE
what bearer token is twitch new api looking ?

### ISSUE THREAD

**Issue by harlick** [nicklaw5/twitch-api-php#81]
Hello, i'm using the last version of this library and i'm trying to get some of the user data. 

case : We have a acces token to a twitch user account after the user enable authentication, we then try to use your library to access his data

```
        $helixGuzzleClient = new HelixGuzzleClient($clientId);
        $apiClient = new NewTwitchApi($helixGuzzleClient, $clientId, $client_secret);
        $apiClient->getUsersApi()->getUserByUsername($accessToken, $name);
```

but the call always end up in failure 
```
Client error: `GET https://api.twitch.tv/helix/users?login=name` resulted in a `401 Unauthorized` response:
{"error":"Unauthorized","status":401,"message":"Invalid OAuth token"}
```

My question is what's the value expect for the bearer token ?

**Comment by echosa** [comment]
@brandinarsenault Can you answer this? I'm still using version 2.x in my own production code, and haven't switched over to the bearer-required version yet. :grimacing:

**Comment by brandinarsenault** [comment]
@harlick you are expected to follow the Authentication requirements outlined here: https://dev.twitch.tv/docs/api/reference#get-users

If you are receiving a 401, your token is, in fact, invalid. I would recommend you reach out to the TwitchDev support for further help on Authentication and debugging: https://link.twitch.tv/devchat

**Comment by echosa** [comment]
Perhaps we should update the README accordingly. A lot of has changed since I last edited it, including version 3.0 of the library.

**Comment by brandinarsenault** [comment]
I was just thinking that :) Glad we're on the same page! I have a few projects on the go so I can't right now, but if I remember in the next few days I'll add some items to it.

**Comment by harlick** [comment]
Can i please have a working example with the helix API ?

**Comment by brandinarsenault** [comment]
```$helixGuzzleClient = new \NewTwitchApi\HelixGuzzleClient($settings->twitch_client_id);
$newTwitchApi = new \NewTwitchApi\NewTwitchApi($helixGuzzleClient, $settings->twitch_client_id, $settings->twitch_client_secret);
$oauth = $newTwitchApi->getOauthApi();

if (isset($_GET['code'])) {
    //Exchange for token
    $response = $oauth->getUserAccessToken($code, 'REDIRECT_URI');
    $responseContent = json_decode($response->getBody()->getContents());
    //Your access token is in the responseContent variable
    $accessToken = $responseContent->access_token;
} else {
    //Generate Oauth URI
    $oauthUri = $oauth->getAuthUrl('REDIRECT_URI', 'code', 'SCOPES - SPACE SEPERATED');
    //Redirect to $oauthUri
}```

**Comment by harlick** [comment]
thank you. I'll keep you update if I fix my issue

**Comment by harlick** [comment]
Hello, sorry for the delay, even with your example I wasn't able to work with the NewApi, I'll switch back to the v5 for now.

Thanks for your time.

**Comment by brandinarsenault** [comment]
@echosa #82 requests the above you noted, this issue should be fine to close.
