### ISSUE TITLE
Twitch API Discord

### ISSUE THREAD

**Issue by brandinarsenault** [nicklaw5/twitch-api-php#85]
Hi @nicklaw5 (CC @echosa) 

I've spoken with a Moderator in the Twitch API Discord (https://discord.gg/8NXaEyV) and they want to add both this and the Go Library (https://github.com/nicklaw5/helix) for the Twitch API as a resource in their server but they make the project owner and collaborators the owners of the channel, so you two would need to be in there and agree to have it added. I wanted to share this here so you can get into this Discord and reach out to Orangutan so he can complete this process.

Thank you,
Brandin.

**Comment by nicklaw5** [comment]
Sorry, I don't understand. What does as adding these libraries as "a resource in their server" actually mean? I'm not on Discord very mush at all. So not sure how much help it would be.

**Comment by echosa** [comment]
Similar to Nick, I'd like to know what exactly this means and what it would do.
