### ISSUE TITLE
How subscribe/unsubscribe from Moderator Change Events

### ISSUE THREAD

**Issue by NormanHuth** [nicklaw5/twitch-api-php#96]
How can I subscribe/unsubscribe from the Webhook Topic Moderator Change Events?
https://dev.twitch.tv/docs/api/webhooks-reference/#topic-moderator-change-events

**Comment by echosa** [comment]
That webhook has not yet been added to the library yet. I'm can't promise it will be added anytime soon. If you would like, you can fork the project, add it, and send a pull request back here. You should just have to add a new method to https://github.com/nicklaw5/twitch-api-php/blob/master/src/NewTwitchApi/Webhooks/WebhooksSubscriptionApi.php.

If you do, please also update the spec: https://github.com/nicklaw5/twitch-api-php/blob/master/spec/NewTwitchApi/Webhooks/WebhooksSubscriptionApiSpec.php

**Comment by NormanHuth** [comment]
OK.

**Comment by NormanHuth** [comment]
I have added the corresponding missing webhook on my system. But I'm still developing and will put a merge request later, because I don't want to do this for every little change.
