### ISSUE TITLE
Proper way to make server-to-server calls

### ISSUE THREAD

**Issue by keithslater** [nicklaw5/twitch-api-php#97]
Ever since Twitch made a change last year, I've been having a problem with server to server calls returning `401 Unauthorized` - `OAuth token is missing`

Is this library updated to handle this type of calls in order to get access tokens? Or do changes still need to be made for it? It looks like the oauth library can handle it, but it doesn't look like NewTwitchApi is using it.

**Comment by echosa** [comment]
I don't understand what you mean by "server to server calls".

**Comment by brandinarsenault** [comment]
In the OAuth Api you use `getAppAccessToken`:
https://github.com/nicklaw5/twitch-api-php/blob/master/src/NewTwitchApi/Auth/OauthApi.php#L108

Make sure to review the OAuth API Docs at Twitch, you would be able to use this to locate the function by searching for `client_credentials` in the project:
https://dev.twitch.tv/docs/authentication/getting-tokens-oauth

**Comment by keithslater** [comment]
Thanks, I've actually been able to do that. What do I do with the app token once I get it? I'm not seeing a way for NewTwitchApi to use it.

**Comment by brandinarsenault** [comment]
If you review the API Docs at Twitch you would note that its considered an access token, so you use it like you would any other token.
